version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - zip -r function.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name readCertificateData --zip-file fileb://function.zip

artifacts:
  files: 'function.zip'